# This is a basic workflow to help you get started with Actions

name: Sync Repo Using Git Commands

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
#     branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: srt32/git-actions@v0.0.3
    - name: Git Sync
      run: |
        git clone https://abdiwan:${{ secrets.SOURCE_SSH_PRIVATE_KEY }}@github.com/abdiwan/demo-repo.git
        cd demo-repo
        git fetch --all
        git checkout dev
        git remote add dest https://${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}@github.com/arbaz-diwan/demo-1.git
        git config --global user.email "arbazd@geekyants.com"
        git config --global user.name "arbaz-diwan"
        git config --local user.password "Abd@9904212533"
        git remote -v
        git add .
        git commit -m "sync repos on push"
        git push dest development
